### ISSUE TITLE
P1 board / case design open source?

### ISSUE THREAD

**Issue by jperquin** [zuidwijk/dsmr#16]
Great work Marcel!

Wondering if the PCB design for the P1 / RJ11 port and the 3D printable case are open source..

I do a lot of custom made ESPHOme stuff, but hate to re-invent te wheel..

Cheers, Joost

**Comment by zuidwijk** [comment]
Hi Joost,

The pcb itself I don't want to publish public. Yet the schematics you can find in my blogs... I'm using a single logic inverter (though a mosfet bs170 can be used too). It's no big secret:

* Use 100uF, 10uF, 1uF and 100nF (in parallel) on the 5 volt rail (needed for the P1 poort, its also listed in the dsmr 5.0.2 requirements)
* Use a pull up resistor between 5v and data line on the P1
* Feed the data through the inverter to the ESP (prefer D7, otherwise Rx will be blocked and the ESP cannot be programmed)

Thats basically it.

**Comment by WhoSayIn** [comment]
Hi @zuidwijk,

Great project! I’m trying to implement mine but couldn’t find the schematics on your blog.

Could you please share a link? Thanks.

**Comment by zuidwijk** [comment]
https://www.zuidwijk.com/p1-esp8266-adapter/

This is the old design. Instead of using Rx I use D7 (IO13). 

Instead of mosfet bs170, I use a logic single inverter. Keep the R5 as pull up for data line. 

And use 100, 10, 1 & 0,1 uF parallel directly on the 5v and gnd from P1 (as documented in the specification)

**Comment by WhoSayIn** [comment]
@zuidwijk thank you so much!

**Comment by zuidwijk** [comment]
> @zuidwijk thank you so much!

Don't forget to use a diode between 5v of P1 and the 5v of the Wemos in case you're feeding 5v via usb ;-)
